const nazmiRoster = {
  "Anaokulu 3 Yaş": [
    "LİSA GÜL",
    "GÜNEŞ KARAKURT",
    "METE HAN YEŞİLYURT",
    "KARYA ÇETİNKAYA",
    "YAĞIZ EFE MUSLU",
    "MİRAÇ ASLAN KEKEÇ",
    "UMAY ARVEN AKGÜL",
    "BERRAK DENİZ KESKİN",
    "DOĞA MORKOÇOĞLU",
    "EYLÜL NEVA DEREBAŞI",
    "MELİS COŞKUN"
  ],
  "Anaokulu 4 Yaş": [
    "UYGAR ALP ÜÇER",
    "ERDİ MURATLI",
    "İPEK KAYA",
    "MUSTAFA ATA KOÇ",
    "MUHAMMET ALİ YILDIRIM",
    "YİĞİT ALP ARSLAN",
    "ECEM SULTAN ALBAYRAK",
    "ÖYKÜ LAÇİN",
    "ATLAS ALİ KELEŞ",
    "ÇİĞDEM EMEK KÜTÜK"
  ],
  "Anaokulu 5 Yaş A": [
    "ARYA ARYAYILDIZLI",
    "BURAK KEMAL GÜRKAN",
    "ÖYKÜ ASYA YÜKSEL",
    "PERA MOR",
    "EYLÜL ÇALIŞ",
    "EVA YILDIRIM",
    "NİL ÜSTÜNGÜN",
    "ALİ MENTEŞOĞLU",
    "UZAY GÜNEŞ",
    "TUĞKAN ÇAĞIN ÇETİN"
  ],
  "Anaokulu 5 Yaş B": [
    "ENİF HUZMELİ",
    "ADİL EFE ÖZKAN",
    "ADEN DİLSİZOĞLU",
    "ZEYNEP ELA AKYÜZ",
    "BURAK HALİM ATİK",
    "URAZ EFE ÖNDER",
    "DURU ACAR",
    "İDİL ERBİLGİN",
    "LALİN ECE POLAT",
    "ELVİN MİLA TAKU",
    "KARAN BERK BARDA",
    "EDA ÇETİN"
  ],
  "1-A": [
    "ALİ BARAN EKMEN",
    "NEHİR MERİÇ",
    "SARE YAVUZ",
    "ATA CAN LÖKÇÜLER",
    "ALP ŞANLI",
    "MİLA YEŞİLDAŞ",
    "YAHYA YAMAN",
    "FEVZİ OZAN ÖZGENÇ",
    "MELEK AĞAÇKIRAN",
    "AHSEN ZEYNEP ALTUNTAŞ",
    "GÜLCE AKGÜN",
    "ALPEREN YAŞAR",
    "ALPARSLAN YAŞAR",
    "CİHANGİR HASAN SARGIN",
    "MARTIN OSMAN BOYRAZ",
    "BEYAZIT ŞİMŞEK",
    "LİYA YILMAZ"
  ],
  "1-B": [
    "CAN ÇAKI",
    "YAĞIZ ARİF ŞENER",
    "KAAN GÜRÖZ",
    "EYLÜL ADA KASAP",
    "İNCİ ERŞAHİN",
    "AYTEN LİYA ÜNAL",
    "YİĞİT ALP AKBULUT",
    "DOĞA KARLIDAĞ",
    "ONUR ABDULLAYEV",
    "BESTE TEKELİ",
    "CEM YAMAN ÜRER",
    "DORUKHAN AÇIK",
    "KUZEY MUTLU",
    "ALİ YİĞİT PAKSOY",
    "DEFNE KAYA",
    "MAKAN KAYA"
  ],
  "2-A": [
    "DEFNE IŞIK",
    "EGE TÜRKEŞ",
    "EYLÜL HAŞARİT",
    "UZAY YAZICI",
    "AHMET TUNA ÜNVER",
    "KUZEY KOÇER",
    "CAN PAMİR ÖZDEMİR",
    "KEREM ARIN YEŞİLBAŞ",
    "DORUK ÜNAL",
    "HANDE ERDOĞAN",
    "MUHAMMET FATİH ÖZTÜRK",
    "KEREM DUMAN",
    "IŞIK ARAS YILDIRIM",
    "NİSA YILDIRIM",
    "KARYA PERK",
    "ÖYKÜ NADİDE ÖNER",
    "GÜNEŞ GÜNAY",
    "LİYA SAYAN",
    "İNCİ KAHYA",
    "BURAK SEYİTOĞLU"
  ],
  "2-B": [
    "ONUR BARIŞ ŞİMŞEK",
    "KAAN KILINÇARSLAN",
    "NAZ AYİN",
    "ZEYNEP İŞKORKUTAN",
    "CAN ALAGÖZ",
    "DERİN SÖYLEMEZ",
    "ÖYKÜ ÇETİNBAŞ",
    "ÖMER ÜSFEKES",
    "ASYA ŞENGÜNLÜ",
    "ANDAÇ KESKİN",
    "DEFNE NİL DEMİR",
    "ATLAS EGE POLAT",
    "KUZEY KARA",
    "İNCİ OMAY",
    "LİSA ÇELİK",
    "NAZAN YILMAZ",
    "GÜNEŞ BÜYÜKTAŞ",
    "NOURA PANAHİ"
  ],
  "3-A": [
    "ALİ ARAS KOÇ",
    "ALİ URAS COŞANSU",
    "ARDA KAĞAN KARABIYIK",
    "ATA ÖZYURT",
    "ATİLLA METE SARIKUŞ",
    "BİLGE KAAN DEMİRKAN",
    "ECE GÜLER",
    "ELA ÖZDEMİR",
    "ELİF BEYZA KOCA",
    "ELİS SADEGHİ",
    "HASAN YİĞİT ALKAN",
    "KAAN ALP ALTAN",
    "MASAL TÜRK",
    "MELİS SÖYLEMEZ",
    "METE ÖZKAN",
    "MİRA KARAGÖL",
    "NEHİR ARSLANYER",
    "YUSUF DEMİRHAN",
    "ZEYNEB MELİKE GÖKDERE",
    "ZEYNEP ALYA MEHMETALİOĞLU",
    "ZEYNEP İPEK ELAMAN"
  ],
  "3-B": [
    "ALİ DEMİR BOZBOĞA",
    "ALİ MERT ARICI",
    "ALYA BALABAN",
    "AMIR OSMONALIEV",
    "ARSHAN YOUSEFİ",
    "ATA AĞAÇKIRAN",
    "AZRA DEMİR",
    "AZRA KAYA",
    "ÇINAR ÇEVİK",
    "DENİZ ÖZGÜL",
    "DURU ERDEM",
    "EBRAR NİSAN KALINEL",
    "EGE ÖZCAN",
    "ELİF AYSİMA ARSLAN",
    "MELİH URAS GENÇ",
    "MİNEL SARE CANDAN",
    "NİL KAYA",
    "NİLSU KOMUTANOĞULLARI",
    "ÖMER MERİÇ BAYDUR",
    "SENA GÜRKAN"
  ],
  "3-C": [
    "ADA DANACI",
    "ASYA LİNA DİKİLİTAŞ",
    "BARLAS DURSUN TELEK",
    "BİLGE DEMİRCİ",
    "BULUT KAYRA ÇİFTÇİ",
    "DERİN ÖZGENÇ",
    "DOĞA ÖZTÜRK",
    "ELİZ YÜCELBAŞ",
    "EMİR KAAN GÜLTEKİN",
    "EYMEN GÜLEMEK",
    "İDİL DENİZ ÖZDOĞAN",
    "İLYA BAYINDIR",
    "İNCİ KOÇ",
    "KUMSAL GÜLER",
    "KUZEY GÜZELARSLAN",
    "MEHMET AYAZ KÖMÜR",
    "POYRAZ DENİZ",
    "SAHRA DÜLDÜL",
    "YASMİN DEMİRCİ",
    "YİĞİT ÖMER MEHMETALİOĞLU"
  ],
  "4-A": [
    "ADAM OMAR MOHAMMAD HISHAM SHAHIN",
    "AREN YAZGI ULUDAĞ",
    "ASİL SEFER",
    "ASİL TÜRK",
    "DENİZ BEREN YILMAZ",
    "DENİZ MADENDERE",
    "DİLŞAD TEZCAN",
    "ELİS NİSA GÜRLEYEN",
    "ERTUĞRUL EVİN",
    "GİRAY ODABAŞ",
    "INJI IMANLI",
    "KAAN KILIÇ",
    "MİLA ŞEN",
    "MUSTAFA MURAT GERDAN",
    "NİL SARE TAFLAN",
    "ÖMER ASAF ALTUNBOĞA",
    "SERDAR DEMİRCİ",
    "SILA DURU ABDİK",
    "YİĞİT İBRAHİM",
    "ZEYNEP ADA ERES"
  ],
  "4-B": [
    "ARAS BAŞKAN",
    "ARYA BAYRAKDAR",
    "ARYA ELA KÖYMEN",
    "DEFNE AYAR",
    "ECE NERGİS ÇETİN",
    "ELİF ADA KIRIKTAŞ",
    "FURKAN ERDOĞAN",
    "LIANA ROUSTAAZAD",
    "MAHDA MOUSAVİ",
    "MAHDYAR MOUSAVİ",
    "MELİKE HAVVA ORTATEPE",
    "MİRAZ ALİ KOÇ",
    "NİL SARA ÇAKMAK",
    "ÖMER ÇİÇEK",
    "ÖMERDEMİR ÖZTÜRK",
    "RASİM EMİR AYDEM",
    "YAĞIZ EFE YAZICI",
    "YUSUF ARAS KIRIKTAŞ",
    "YUSUF KIYIŞKAN",
    "ZEYNEP TAŞDEMİR"
  ]
};
module.exports = { nazmiRoster };
