const {test}=require('node:test');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
for (const entry of ['server/local.cjs', 'tests/vercel-host.mjs']) test(entry + ': Oturum, yetki, formlar, görüşmeler, Excel ve kalıcılık',async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rehberlik-test-'));
  let child,base;
  async function start(){child=spawn(process.execPath,[entry],{cwd:__dirname,env:{...process.env,DATA_DIR:dir,PORT:'0',VERCEL:'',TURSO_DATABASE_URL:'',TURSO_AUTH_TOKEN:'',EDITOR_PASSWORD:'123456',TUGBA_EDITOR_PASSWORD:'tugba-test',KUBRA_EDITOR_PASSWORD:'kubra-test',SELIN_EDITOR_PASSWORD:'selin-test'},stdio:['ignore','pipe','pipe']});base=await new Promise((resolve,reject)=>{let out='';child.stdout.on('data',b=>{out+=b;const m=out.match(/http:\/\/localhost:(\d+)/);if(m)resolve(`http://127.0.0.1:${m[1]}`);});child.on('error',reject);child.on('exit',code=>reject(new Error('Server exited: '+code)));});}
  async function stop(){if(child.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});}
  async function request(route,method='GET',body,cookie,extraHeaders={}){const r=await fetch(base+route,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...extraHeaders},body:body?JSON.stringify(body):undefined});const bytes=Buffer.from(await r.arrayBuffer());return {status:r.status,headers:r.headers,cookie:r.headers.get('set-cookie')?.split(';')[0],data:r.headers.get('content-type')?.includes('json')?JSON.parse(bytes):bytes};}
  try{
    await start();
    assert.equal((await request('/api/data')).status,401);
    assert.equal((await request('/api/login','POST',{username:'ilaydahisarbeyli',password:'wrong'})).status,401);
    const guest=(await request('/api/login','POST',{guest:true})).cookie;
    const editorLogin=await request('/api/login','POST',{username:'ilaydahisarbeyli',password:'123456'}),editor=editorLogin.cookie;
    const tugbaLogin=await request('/api/login','POST',{username:'tugbasaygi',password:'tugba-test'}),tugba=tugbaLogin.cookie;
    const kubra=(await request('/api/login','POST',{username:'kubrakaban',password:'kubra-test'})).cookie;
    const selin=(await request('/api/login','POST',{username:'selinak',password:'selin-test'})).cookie;
    assert.equal(editorLogin.data.user.name,'İlayda Hisarbeyli');assert.equal(tugbaLogin.data.user.name,'Tuğba Saygı');
    const schools=(await request('/api/schools','GET',null,guest)).data;
    assert.deepEqual(schools.map(s=>[s.id,s.classCount]),[['nazmi',13],['atagen',8]]);
    assert.deepEqual((await request('/api/schools','GET',null,tugba)).data.map(s=>[s.id,s.classCount]),[['nazmi',4]]);
    assert.deepEqual((await request('/api/schools','GET',null,kubra)).data.map(s=>[s.id,s.classCount]),[['nazmi',4]]);
    assert.deepEqual((await request('/api/schools','GET',null,selin)).data.map(s=>[s.id,s.classCount]),[['nazmi',5]]);
    assert.equal((await request('/api/data','GET',null,guest)).data.school.id,'nazmi');
    const d=(await request('/api/data?schoolId=nazmi','GET',null,guest)).data;
    const atagen=(await request('/api/data?schoolId=atagen','GET',null,guest)).data;
    assert.equal(d.school.id,'nazmi');assert.equal(d.classes.length,13);assert.equal(d.students.length,215);
    assert.equal(atagen.school.id,'atagen');assert.equal(atagen.classes.length,8);assert.equal(atagen.students.length,94);
    assert.equal(d.teachers.length,35);assert.ok(d.teachers.includes('Esra Derebaşı'));assert.ok(d.teachers.includes('Beyza Es'));assert.ok(d.teachers.includes('Özgür Emil'));assert.ok(d.teachers.includes('Eda Aktaş'));assert.ok(!d.teachers.includes('Ayşe Kaya'));
    assert.equal(atagen.teachers.length,25);assert.ok(atagen.teachers.includes('Mehtap Duyan'));assert.ok(atagen.teachers.includes('Beyza Es'));assert.ok(atagen.teachers.includes('Özgür Emil'));assert.ok(!atagen.teachers.includes('Esra Derebaşı'));
    assert.deepEqual(Object.fromEntries(d.classes.map(item=>[item.name,item.teacher])),{'Anaokulu 3 Yaş':'Sıla Konukçu','Anaokulu 4 Yaş':'Elif Gaye Dingil','Anaokulu 5 Yaş A':'Esra Derebaşı','Anaokulu 5 Yaş B':'Sema Kesik','1-A':'Mehmet Baytekin','1-B':'Berkay Meç','2-A':'Hüsniye Berk','2-B':'Beste Günçiçek','3-A':'Doğuş Aydın','3-B':'Dilek Güngör','3-C':'İlker Bayraktar','4-A':'Çiğdem Uzunçakmak','4-B':'Fadime Karataş'});
    assert.deepEqual(Object.fromEntries(atagen.classes.map(item=>[item.name,item.teacher])),{'Anaokulu 3 Yaş':'Yaren Palalıoğlu','Anaokulu 4 Yaş':'Rabia Akgül','Anaokulu 5 Yaş':'Hazal Durgut','1-A':'Şahinde Köksal','2-A':'Rozerin Furan','3-A':'Mehtap Duyan','4-A':'Hamit Sarı','4-B':'Zeynep Betül Şimşek'});
    const tugbaData=(await request('/api/data?schoolId=nazmi','GET',null,tugba)).data;assert.deepEqual(tugbaData.classes.map(c=>c.name),['Anaokulu 3 Yaş','Anaokulu 4 Yaş','Anaokulu 5 Yaş A','Anaokulu 5 Yaş B']);assert.equal(tugbaData.students.length,43);
    const kubraData=(await request('/api/data?schoolId=nazmi','GET',null,kubra)).data;assert.deepEqual(kubraData.classes.map(c=>c.name),['1-A','1-B','2-A','2-B']);assert.equal(kubraData.students.length,71);
    const selinData=(await request('/api/data?schoolId=nazmi','GET',null,selin)).data;assert.deepEqual(selinData.classes.map(c=>c.name),['3-A','3-B','3-C','4-A','4-B']);assert.equal(selinData.students.length,101);
    assert.equal((await request('/api/data?schoolId=atagen','GET',null,tugba)).status,403);
    assert.equal((await request('/api/export?schoolId=atagen','GET',null,kubra)).status,403);
    const expectedClassCounts={'Anaokulu 3 Yaş':11,'Anaokulu 4 Yaş':10,'Anaokulu 5 Yaş A':10,'Anaokulu 5 Yaş B':12,'1-A':17,'1-B':16,'2-A':20,'2-B':18,'3-A':21,'3-B':20,'3-C':20,'4-A':20,'4-B':20};
    for(const c of d.classes)assert.equal(d.students.filter(s=>s.classId===c.id).length,expectedClassCounts[c.name]);
    const expectedAtagenClassCounts={'Anaokulu 3 Yaş':6,'Anaokulu 4 Yaş':11,'Anaokulu 5 Yaş':11,'1-A':13,'2-A':12,'3-A':11,'4-A':15,'4-B':15};
    for(const c of atagen.classes)assert.equal(atagen.students.filter(s=>s.classId===c.id).length,expectedAtagenClassCounts[c.name]);
    assert.ok(d.students.some(student=>student.name==='ALİ BARAN EKMEN'&&student.classId==='nazmi-1a'));
    assert.ok(d.students.some(student=>student.name==='LİYA YILMAZ'&&student.classId==='nazmi-1a'));
    assert.ok(d.students.some(student=>student.name==='KARAN BERK BARDA'&&student.classId==='nazmi-anaokulu5yasb'));
    assert.ok(d.students.some(student=>student.name==='EDA ÇETİN'&&student.classId==='nazmi-anaokulu5yasb'));
    for(const name of ['BERRAK DENİZ KESKİN','DOĞA MORKOÇOĞLU','EYLÜL NEVA DEREBAŞI','MELİS COŞKUN'])assert.equal(d.students.filter(student=>student.name===name&&student.classId==='nazmi-anaokulu3yas').length,1);
    for(const name of ['ÖYKÜ LAÇİN','İPEK KAYA','YİĞİT ALP ARSLAN','MUHAMMET ALİ YILDIRIM'])assert.equal(d.students.filter(student=>student.name===name&&student.classId==='nazmi-anaokulu4yas').length,1);
    assert.equal(d.students.filter(student=>student.name==='BEYAZIT ŞİMŞEK'&&student.classId==='nazmi-1a').length,1);
    assert.ok(d.students.every(student=>student.birthDate===''&&student.gender==='Belirtilmedi'&&student.parentName===''&&student.phone===''));
    assert.ok(atagen.students.some(student=>student.name==='ADEN DURU AĞCA'&&student.classId==='atagen-anaokulu3yas'));
    assert.ok(atagen.students.some(student=>student.name==='LEYLA TOKUŞ'&&student.classId==='atagen-anaokulu3yas'));
    assert.ok(atagen.students.some(student=>student.name==='NİL AĞAN'&&student.classId==='atagen-anaokulu4yas'));
    assert.ok(atagen.students.some(student=>student.name==='OĞUZHAN KONCA'&&student.classId==='atagen-anaokulu5yas'));
    assert.ok(atagen.students.some(student=>student.name==='ZEYNEP ERÇEVİK'&&student.classId==='atagen-4a'));
    assert.ok(atagen.students.some(student=>student.name==='ALİ HAKKI'&&student.classId==='atagen-4b'));
    assert.ok(atagen.students.every(student=>student.birthDate===''&&student.gender==='Belirtilmedi'&&student.parentName===''&&student.phone===''));
    assert.equal(d.students.some(s=>atagen.students.some(a=>a.id===s.id)),false);
    assert.equal('meetings' in d,false);assert.deepEqual(d.records,[]);assert.equal(d.rubricCriteria.length,21);assert.equal(d.rubricScale.length,5);
    const sid=d.students[0].id;
    const firstGradeSid=d.students.find(student=>student.classId==='nazmi-1a').id;
    const portalOrigin='https://veli-bilgi-formlari-kagithane.vercel.app';
    const parentSetup=await request('/api/parent-form','GET',null,null,{Origin:portalOrigin});assert.equal(parentSetup.status,200);assert.equal(parentSetup.headers.get('access-control-allow-origin'),portalOrigin);assert.equal(parentSetup.data.schools.length,2);assert.equal(parentSetup.data.questions.length,4);
    const preflight=await request('/api/parent-form','OPTIONS',null,null,{Origin:portalOrigin,'Access-Control-Request-Method':'POST'});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),portalOrigin);
    const parentPayload={schoolId:'nazmi',className:d.classes.find(item=>item.id===d.students[0].classId).name.replace('-',''),studentName:d.students[0].name.toLocaleUpperCase('tr'),respondentName:'Deneme Veli',relationship:'Anne',answers:{strengths:'İletişimi güçlü.',supportNeeds:'Planlama desteği gerekiyor.',homeRoutine:'Akşam kısa çalışmalar yapıyor.',schoolNotes:'VELI_GIZLI deneme yanıtı.'}};
    assert.equal((await request('/api/parent-form','POST',{...parentPayload,studentName:'Eşleşmeyen Öğrenci'})).status,404);
    assert.equal((await request('/api/parent-form','POST',{...parentPayload,answers:{...parentPayload.answers,strengths:''}})).status,400);
    assert.equal((await request('/api/parent-form','POST',{...parentPayload,website:'bot'},null,{Origin:portalOrigin,'Sec-Fetch-Site':'cross-site'})).status,201);
    assert.equal((await request('/api/parent-form','POST',parentPayload,null,{Origin:'https://example.com','Sec-Fetch-Site':'cross-site'})).status,403);
    assert.equal((await request('/api/parent-form','POST',parentPayload)).status,201);
    assert.equal((await request('/api/parent-forms?studentId='+sid)).status,401);
    assert.equal((await request('/api/parent-forms?studentId='+sid,'GET',null,guest)).status,403);
    const parentForms=(await request('/api/parent-forms?studentId='+sid,'GET',null,editor)).data;assert.equal(parentForms.length,1);assert.equal(parentForms[0].respondentName,'Deneme Veli');assert.ok(parentForms[0].answers.some(answer=>answer.value.includes('VELI_GIZLI')));
    assert.equal((await request('/api/parent-forms?studentId='+sid,'GET',null,tugba)).status,200);
    assert.equal((await request('/api/parent-forms?studentId='+sid,'GET',null,kubra)).status,403);
    assert.equal((await request('/api/parent-forms/'+parentForms[0].id+'/pdf','GET',null,guest)).status,403);
    const parentPdf=await request('/api/parent-forms/'+parentForms[0].id+'/pdf','GET',null,tugba);assert.equal(parentPdf.status,200);assert.ok(parentPdf.data.subarray(0,5).equals(Buffer.from('%PDF-')));assert.match(parentPdf.headers.get('content-disposition'),/veli-bilgi-formu-/);
    assert.equal((await request('/api/parent-form','POST',{...parentPayload,respondentName:'Silinecek Veli'})).status,201);
    const removableParent=(await request('/api/parent-forms?studentId='+sid,'GET',null,editor)).data.find(item=>item.respondentName==='Silinecek Veli');assert.ok(removableParent);
    assert.equal((await request('/api/parent-forms/'+removableParent.id,'DELETE',{},guest)).status,403);
    assert.equal((await request('/api/parent-forms/'+removableParent.id,'DELETE',{},kubra)).status,403);
    assert.equal((await request('/api/parent-forms/'+removableParent.id,'DELETE',{},tugba)).status,200);
    assert.equal((await request('/api/parent-forms/'+removableParent.id,'DELETE',{},editor)).status,404);
    const weeklyMeeting={schoolId:'nazmi',date:'2026-09-05',teacherNames:[d.teachers[0],d.teachers[1]],topics:'K'.repeat(12000)};
    assert.equal((await request('/api/weekly-meetings?schoolId=nazmi')).status,401);
    assert.equal((await request('/api/weekly-meetings','POST',weeklyMeeting,guest)).status,403);
    assert.equal((await request('/api/weekly-meetings','POST',{...weeklyMeeting,teacherNames:['Tanımsız Öğretmen']},editor)).status,400);
    assert.equal((await request('/api/weekly-meetings','POST',weeklyMeeting,editor)).status,201);
    const weeklyRows=(await request('/api/weekly-meetings?schoolId=nazmi','GET',null,tugba)).data;assert.equal(weeklyRows.length,1);assert.deepEqual(weeklyRows[0].teacherNames,weeklyMeeting.teacherNames);assert.equal(weeklyRows[0].createdByName,'İlayda Hisarbeyli');
    assert.equal((await request('/api/weekly-meetings?schoolId=atagen','GET',null,tugba)).status,403);
    assert.equal((await request('/api/meetings?studentId='+sid,'GET',null,guest)).status,403);
    const profile={birthDate:'2023-04-03',gender:'Kız',parentName:'Örnek Veli',phone:'555 000 00 00'};
    assert.equal((await request('/api/students/'+sid,'PUT',profile,guest)).status,403);
    assert.equal((await request('/api/students/'+sid,'PUT',profile,editor)).status,200);
    assert.equal((await request('/api/students/'+sid,'PUT',profile,tugba)).status,200);
    assert.equal((await request('/api/students/'+firstGradeSid,'PUT',profile,tugba)).status,403);
    assert.equal((await request('/api/meetings?studentId='+firstGradeSid,'GET',null,tugba)).status,403);
    assert.equal((await request('/api/students/'+sid,'PUT',{...profile,birthDate:'2023-02-31'},editor)).status,400);
    const form={studentId:sid,teacher:d.teachers[0],date:'2026-09-03',type:'Genel Gözlem',frequency:'Yaklaşık iki haftadır, her gün',previousActions:'Sınıf içinde kısa hatırlatmalar yaptım.',note:'=Örnek & <metin>\nİkinci satır'};
    const observationCreated=await request('/api/records','POST',{...form,kind:'observation'},guest);assert.equal(observationCreated.status,201);
    assert.equal((await request('/api/records','POST',{...form,kind:'observation',teacher:'Ayşe Kaya'},guest)).status,400);
    assert.equal((await request('/api/records','POST',{...form,studentId:atagen.students[0].id,kind:'observation',teacher:'Esra Derebaşı'},guest)).status,400);
    assert.equal((await request('/api/records','POST',{...form,kind:'observation',frequency:''},guest)).status,400);
    assert.equal((await request('/api/records','POST',{...form,kind:'parent'},guest)).status,400);
    const ratings=Object.fromEntries(d.rubricCriteria.map(item=>[item.code,'3']));
    const rubricCreated=await request('/api/records','POST',{studentId:sid,kind:'rubric',teacher:d.teachers[0],date:'2026-09-03',ratings,note:'Genel gözlem notu'},guest);assert.equal(rubricCreated.status,201);
    assert.equal((await request('/api/records','POST',{studentId:sid,kind:'rubric',teacher:d.teachers[0],date:'2026-09-03',ratings:{A1:'3'},note:''},guest)).status,400);
    assert.equal((await request('/api/data?schoolId=nazmi','GET',null,tugba)).data.records.length,2);
    assert.equal((await request('/api/data?schoolId=nazmi','GET',null,kubra)).data.records.length,0);
    assert.equal((await request('/api/records','POST',{...form,studentId:firstGradeSid,kind:'observation'},tugba)).status,403);
    assert.equal((await request('/api/records/'+observationCreated.data.id+'/pdf','GET',null,guest)).status,403);
    assert.equal((await request('/api/records/'+observationCreated.data.id+'/pdf','GET',null,kubra)).status,403);
    const observationPdf=await request('/api/records/'+observationCreated.data.id+'/pdf','GET',null,tugba);assert.equal(observationPdf.status,200);assert.equal(observationPdf.headers.get('content-type'),'application/pdf');assert.ok(observationPdf.data.subarray(0,5).equals(Buffer.from('%PDF-')));assert.match(observationPdf.headers.get('content-disposition'),/gozlem-formu-/);
    const rubricPdf=await request('/api/records/'+rubricCreated.data.id+'/pdf','GET',null,editor);assert.equal(rubricPdf.status,200);assert.ok(rubricPdf.data.subarray(0,5).equals(Buffer.from('%PDF-')));
    const removable=await request('/api/records','POST',{...form,kind:'observation',note:'Silinecek deneme yanıtı'},guest);assert.equal(removable.status,201);
    assert.equal((await request('/api/records/'+removable.data.id,'DELETE',{},guest)).status,403);
    assert.equal((await request('/api/records/'+removable.data.id,'DELETE',{},kubra)).status,403);
    assert.equal((await request('/api/records/'+removable.data.id,'DELETE',{},tugba)).status,200);
    assert.equal((await request('/api/records/'+removable.data.id,'DELETE',{},editor)).status,404);
    const ids=[];
    for(const kind of ['student','parent']){
      const m={studentId:sid,kind,date:'2026-09-03',participant:'Örnek Katılımcı',subject:'Takip',note:'GİZLİ görüşme notu'};
      assert.equal((await request('/api/meetings','POST',m,guest)).status,403);
      const created=await request('/api/meetings','POST',m,editor);assert.equal(created.status,201);ids.push(created.data.id);
    }
    assert.equal((await request('/api/meetings?studentId='+sid,'GET',null,editor)).data.length,2);
    const secondPreschoolSid=d.students.find(student=>student.classId==='nazmi-anaokulu4yas').id;
    const group={studentIds:[sid,secondPreschoolSid],kind:'student',format:'group',status:'completed',date:'2026-09-04',subject:'Sosyal-Duygusal',note:'Sıra alma çalışması yapıldı.'};
    assert.equal((await request('/api/interviews','POST',group,guest)).status,403);
    const groupCreated=await request('/api/interviews','POST',group,tugba);assert.equal(groupCreated.status,201);
    assert.equal((await request('/api/interviews','POST',{...group,studentIds:[sid]},tugba)).status,400);
    assert.equal((await request('/api/interviews','POST',{...group,studentIds:[sid,firstGradeSid]},tugba)).status,403);
    assert.ok((await request('/api/meetings?studentId='+sid,'GET',null,tugba)).data.some(item=>item.id===groupCreated.data.id&&item.students.length===2));
    assert.ok((await request('/api/meetings?studentId='+secondPreschoolSid,'GET',null,tugba)).data.some(item=>item.id===groupCreated.data.id));
    const appointment={studentIds:[firstGradeSid],kind:'parent',format:'individual',status:'appointment',date:'2026-09-10',time:'14:30',subject:'Genel Görüşme',note:'Kısa hazırlık notu'};
    assert.equal((await request('/api/interviews','POST',{...appointment,time:''},kubra)).status,400);
    const appointmentCreated=await request('/api/interviews','POST',appointment,kubra);assert.equal(appointmentCreated.status,201);
    const allInterviews=(await request('/api/interviews?schoolId=nazmi','GET',null,editor)).data;assert.equal(allInterviews.length,4);assert.ok(allInterviews.some(item=>item.id===appointmentCreated.data.id&&item.status==='appointment'));
    assert.ok(!(await request('/api/interviews?schoolId=nazmi','GET',null,tugba)).data.some(item=>item.id===appointmentCreated.data.id));
    assert.equal((await request('/api/interviews/'+groupCreated.data.id,'DELETE',{},kubra)).status,403);
    assert.equal((await request('/api/meetings/'+ids[0],'DELETE',{},guest)).status,403);
    assert.equal((await request('/api/meetings/'+ids[0],'DELETE',{},editor)).status,200);
    assert.equal((await request('/api/export?schoolId=nazmi','GET',null,guest)).status,403);
    assert.equal((await request('/api/export?schoolId=nazmi&classId=nazmi-1a','GET',null,tugba)).status,403);
    const exported=await request('/api/export?schoolId=nazmi','GET',null,editor);assert.equal(exported.status,200);assert.equal(exported.data.readUInt32LE(0),0x04034b50);assert.ok(exported.data.includes(Buffer.from('=Örnek &amp; &lt;metin&gt;')));assert.ok(exported.data.includes(Buffer.from('Cevap: 3 — Bağımsız Sergiliyor')));assert.ok(!exported.data.includes(Buffer.from('GİZLİ')));
    const observationExport=await request('/api/export?schoolId=nazmi&kind=observation','GET',null,editor);assert.equal(observationExport.status,200);assert.ok(observationExport.data.includes(Buffer.from('=Örnek &amp; &lt;metin&gt;')));assert.ok(!observationExport.data.includes(Buffer.from(d.rubricCriteria[0].behavior)));
    const rubricExport=await request('/api/export?schoolId=nazmi&kind=rubric','GET',null,editor);assert.equal(rubricExport.status,200);assert.ok(rubricExport.data.includes(Buffer.from(d.rubricCriteria[0].behavior)));assert.ok(rubricExport.data.includes(Buffer.from('3 — Bağımsız Sergiliyor')));assert.ok(!rubricExport.data.includes(Buffer.from('=Örnek')));const rubricXml=rubricExport.data.toString('utf8');assert.equal((rubricXml.match(/<row r="/g)||[]).length,2);assert.ok(rubricXml.includes('r="AA1"'));assert.ok(rubricXml.includes('autoFilter ref="A1:AA2"'));
    assert.equal((await request('/api/export?schoolId=nazmi&kind=unknown','GET',null,editor)).status,400);
    assert.equal((await request('/data/rehberlik.sqlite')).status,404);assert.equal((await request('/server.cjs')).status,404);
    const publicData=JSON.stringify((await request('/api/data?schoolId=nazmi','GET',null,guest)).data);assert.ok(!publicData.includes('GİZLİ'));assert.ok(!publicData.includes('=Örnek'));assert.ok(!publicData.includes('VELI_GIZLI'));
    await request('/api/logout','POST',{},editor);assert.equal((await request('/api/meetings?studentId='+sid,'GET',null,editor)).status,401);
    await stop();await start();
    assert.equal((await request('/api/session','GET',null,guest)).data.role,'guest');
    assert.equal((await request('/api/session','GET',null,editor)).data.role,null);
    const tugbaSession=(await request('/api/session','GET',null,tugba)).data;assert.equal(tugbaSession.role,'editor');assert.equal(tugbaSession.user.name,'Tuğba Saygı');
    const again=(await request('/api/login','POST',{username:'ilaydahisarbeyli',password:'123456'})).cookie;
    const saved=(await request('/api/data?schoolId=nazmi','GET',null,again)).data;assert.equal(saved.records.length,2);assert.equal(saved.records.filter(r=>r.kind==='rubric').length,1);assert.equal(saved.students[0].parentName,'Örnek Veli');assert.equal((await request('/api/meetings?studentId='+sid,'GET',null,again)).data.length,2);assert.equal((await request('/api/parent-forms?studentId='+sid,'GET',null,again)).data.length,1);assert.equal((await request('/api/weekly-meetings?schoolId=nazmi','GET',null,again)).data.length,1);
  }finally{if(child)await stop();fs.rmSync(dir,{recursive:true,force:true});}
});
